server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    instance-id: front-api
    hostname: localhost
    prefer-ip-address: true
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
