server:
  port: 8080

eureka:
  instance:
    instance-id: front-api-1
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:1234@eureka-server:8761/eureka