spring:
  application:
    name: front-api
  cloud:
    loadbalancer:
      retry:
        enabled: true
  profiles:
    active: dev

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    instance-id: front-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:1234@eureka-server:8761/eureka

secret:
  url: https://api-keymanager.nhncloudservice.com
  appKey: qTQNj7LyHhdAazH3
  keys:
    payco:
      client-id: 9ae8d7047d614e2d8676715111dcb443
      client-secret: 079b482168044c9abe902c578aae31a1
  password: nhn24


server:
  servlet:
    context-path: /frontend